# Generated by Django 3.2.8 on 2021-12-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_results_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='today_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='today_price',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
